"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Layout/Navbar";
import Footer from "@/Components/Layout/Footer";

import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import ReduxProvider from "@/Components/providers/ReduxProvider";
import AuthProvider from "@/Components/providers/AuthProvider";
// import ReduxProvider from "@/Components/providers/ReduxProvider";
// import AuthProvider from "@/Components/providers/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#f7f6f2] dark:bg-[#212121]">
        {/* <Provider store={store}>
          <Navbar />
          {children}
          <Footer />
        </Provider> */}
        <ReduxProvider>
          <Navbar />
          <AuthProvider>{children}</AuthProvider>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
